name: first workflow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "example workflow"
      - name: Checkout Repo
        uses: actions/checkout@v5.0.0
      - name: List repository files
        run: ls -la
