name: test workflow
on:
    push:
        branches:
            - main
            - 'release/**'
        paths:
            - 'src/**'
            - 'code/**'
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v5.0.0
            - name: Run tests
              run: npm test
