name: test workflow
on:
    push:
        branches:
            - main
            - 'release/**'
        paths:
            - 'src/**'
            - 'code/**'
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v5.0.0
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.